const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dashBridge', {
  onSessions: (cb) => ipcRenderer.on('dash-sessions', (_e, data) => cb(data)),
  onSoundState: (cb) => ipcRenderer.on('sound-state', (_e, data) => cb(data)),
  toggleSound: () => ipcRenderer.send('sound-toggle'),
  ready: () => ipcRenderer.send('dash-ready'),
  getPacks: () => ipcRenderer.invoke('packs-get'),
  setSessionPack: (sessionId, name) => ipcRenderer.invoke('packs-set-session', sessionId, name),
  setVolume: (v) => ipcRenderer.invoke('packs-set-volume', v),
  setCategory: (cat, on) => ipcRenderer.invoke('packs-set-category', cat, on),
  setNotifications: (on) => ipcRenderer.invoke('packs-set-notifications', on),
  getPixoo: () => ipcRenderer.invoke('pixoo-get'),
  setPixoo: (cfg) => ipcRenderer.invoke('pixoo-set', cfg),
  onPixooState: (cb) => ipcRenderer.on('pixoo-state', (_e, d) => cb(d)),
  getPets: () => ipcRenderer.invoke('pets-get'),
  createPets: (input) => ipcRenderer.invoke('pets-create', input),
  updatePet: (id, patch) => ipcRenderer.invoke('pets-update', id, patch),
  removePet: (id) => ipcRenderer.invoke('pets-remove', id),
  setLead: (id) => ipcRenderer.invoke('pets-set-lead', id),
  updateSpecies: (slug, patch) => ipcRenderer.invoke('species-update', slug, patch),
  createDraft: (input) => ipcRenderer.invoke('species-create-draft', input),
  removeDraft: (slug) => ipcRenderer.invoke('species-remove-draft', slug),
  genPrompt: (req) => ipcRenderer.invoke('gen-prompt', req),
  importSheet: (req) => ipcRenderer.invoke('species-import', req),
  importExtra: (req) => ipcRenderer.invoke('extra-import', req),
  previewSheet: (slug) => ipcRenderer.invoke('species-preview', slug),
  importEnv: (req) => ipcRenderer.invoke('env-import', req),
  updateEnv: (id, patch) => ipcRenderer.invoke('env-update', id, patch),
  removeEnv: (id) => ipcRenderer.invoke('env-remove', id),
  setBorder: (id) => ipcRenderer.invoke('borders-set', id),
  getCornerView: () => ipcRenderer.invoke('corner-get'),
  setCornerView: (v) => ipcRenderer.send('corner-set-view', v),
  onCornerView: (cb) => ipcRenderer.on('corner-view', (_e, v) => cb(v)),
  getProjects: () => ipcRenderer.invoke('projects-get'),
  updateProject: (key, patch) => ipcRenderer.invoke('projects-update', key, patch),
  assignProject: (id, key) => ipcRenderer.invoke('projects-assign', id, key),
  forgetProject: (key) => ipcRenderer.invoke('projects-forget', key),
  getFirm: () => ipcRenderer.invoke('firm-get'),
  setFirm: (cfg) => ipcRenderer.invoke('firm-set', cfg),
  onFirmState: (cb) => ipcRenderer.on('firm-state', (_e, d) => cb(d)),
  getForge: () => ipcRenderer.invoke('forge-get'),
  setForgeTint: (role, tint) => ipcRenderer.invoke('forge-set-tint', role, tint),
  setForgeRole: (role, species) => ipcRenderer.invoke('forge-set', role, species),
  getTypes: () => ipcRenderer.invoke('types-get'),
  putType: (t) => ipcRenderer.invoke('types-put', t),
  removeType: (slug) => ipcRenderer.invoke('types-remove', slug),
  pinType: (kind, key, slug) => ipcRenderer.invoke('types-pin', kind, key, slug),
  setAutoRoots: (on) => ipcRenderer.invoke('types-auto-roots', on),
  checkType: (slug, action) => ipcRenderer.invoke('types-check', slug, action),
  openGrid: (view) => ipcRenderer.send('open-grid', view),
  audition: (name) => ipcRenderer.invoke('packs-audition', name),
  setGlobalPack: (name, applyToSessions) => ipcRenderer.invoke('packs-set-global', name, applyToSessions),
});
