const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('dashBridge', {
  onSessions: (cb) => ipcRenderer.on('dash-sessions', (_e, data) => cb(data)),
  onSoundState: (cb) => ipcRenderer.on('sound-state', (_e, data) => cb(data)),
  toggleSound: () => ipcRenderer.send('sound-toggle'),
  ready: () => ipcRenderer.send('dash-ready'),
  getPacks: () => ipcRenderer.invoke('packs-get'),
  setSessionPack: (sessionId, name) => ipcRenderer.invoke('packs-set-session', sessionId, name),
  setVolume: (v) => ipcRenderer.invoke('packs-set-volume', v),
  setCategory: (cat, on) => ipcRenderer.invoke('packs-set-category', cat, on),
  setNotifications: (on) => ipcRenderer.invoke('packs-set-notifications', on),
  getPixoo: () => ipcRenderer.invoke('pixoo-get'),
  setPixoo: (cfg) => ipcRenderer.invoke('pixoo-set', cfg),
  onPixooState: (cb) => ipcRenderer.on('pixoo-state', (_e, d) => cb(d)),
  getPets: () => ipcRenderer.invoke('pets-get'),
  createPets: (input) => ipcRenderer.invoke('pets-create', input),
  updatePet: (id, patch) => ipcRenderer.invoke('pets-update', id, patch),
  removePet: (id) => ipcRenderer.invoke('pets-remove', id),
  setLead: (id) => ipcRenderer.invoke('pets-set-lead', id),
  updateSpecies: (slug, patch) => ipcRenderer.invoke('species-update', slug, patch),
  createDraft: (input) => ipcRenderer.invoke('species-create-draft', input),
  removeDraft: (slug) => ipcRenderer.invoke('species-remove-draft', slug),
  genPrompt: (req) => ipcRenderer.invoke('gen-prompt', req),
  importSheet: (req) => ipcRenderer.invoke('species-import', req),
  importExtra: (req) => ipcRenderer.invoke('extra-import', req),
  previewSheet: (slug) => ipcRenderer.invoke('species-preview', slug),
  importEnv: (req) => ipcRenderer.invoke('env-import', req),
  updateEnv: (id, patch) => ipcRenderer.invoke('env-update', id, patch),
  removeEnv: (id) => ipcRenderer.invoke('env-remove', id),
  setBorder: (id) => ipcRenderer.invoke('borders-set', id),
  openGrid: () => ipcRenderer.send('open-grid'),
  audition: (name) => ipcRenderer.invoke('packs-audition', name),
  setGlobalPack: (name, applyToSessions) => ipcRenderer.invoke('packs-set-global', name, applyToSessions),
});
